apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: roneyrogerio.dev
  namespace: curriculum
spec:
  ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: curriculum
